/* Example Sorter
–––––––––––––––––––––––––––––––––––––––––––––––––– */
// Note: _id is the primary key generated by all MongoDB documents.
// The one below is a test key of approximately the same length.
// {
//   _id: "511bde3e3985283f25000004",
//   name: "MountainSort4-thr3",
//   processorName: "MountainSort4",
//   version: "4.1.0",
//   sortingParameters: {
//      detectRadius: 1
//   }
// }

const mongoose = require("mongoose");
mongoose.Promise = global.Promise;

const sorterSchema = new mongoose.Schema({
  name: {
    type: String,
    required: "You must provide a name for the sorter."
  },
  algorithm: {
    type: String
  },
  processorName: {
    type: String,
    required: "You must provide a processor name for the sorter."
  },
  version: {
    type: String,
    required: "You must provide a version for the sorter."
  },
  sortingParameters: {
    type: Object,
    required: "You must provide sorting params please."
  }
});

module.exports = mongoose.model("Sorter", sorterSchema);
